import axios from 'axios'
import Head from 'next/head'
import Image from 'next/image'
import About from '../components/About'
import PlantsList from '../components/PlantsList'
import styles from '../styles/Home.module.css'

export default function Home ({plantsList}) {
  console.log(plantsList)
  return (
    <div className={styles.container}>
      <Head>
        <title>Plant's - Магазин ростений</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className={styles.section}>
        <div className={styles.container}>
          <div className={styles.home__continer}>
            <div className={styles.home__content}>
              <h1  className={styles.home__title}>Plants will make your life better</h1>
              <span  className={styles.home__description}>Create incredible plant design for your offices or
              apastaments. Add fresness to your new ideas.</span>
              <button  className={styles.home__btn}>Explore</button>
            </div>
            <div className={styles.home__img}>
              <Image src="/img/home.png" alt='' width='400px' height='400px'/>
            </div>
          </div>
        </div>
      </section>
      <About/>
      <PlantsList plantsList={plantsList} />
    </div>
  )
}

export const getServerSideProps = async () => {
  const res = await axios.get(`http://localhost:3000/api/products`)
  return {
    props: {
      plantsList: res.data,
    },
  };
};
